version: "3.9"

services:
  telegram_app:
    container_name: telegram-plash-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/telegram_app
    env_file:
      - .env
    command: > 
      sh -c "python manage.py wait_for_db_script && 
      python manage.py migrate && 
      python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    networks:
      - my_network

  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: >
      sh -c 'python telegram_bot/run.py'
    depends_on:
      - telegram_app
    networks:
      - my_network

  db:
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db:$PGDATA
    networks:
      - my_network

volumes:
  db:

networks:
  my_network:
    driver: bridge